id: I4E00F474
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-2aec
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 18:00:23.854558+00:00
last_modified: 2023-09-28 18:00:23.854566+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN26858
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN26858
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བྱང་ཆུབ་ལམ་སྒྲོན་གྱི་འགྲེལ་པ་མར་གྱི་ཉིང་ཁུ།
  languages:
  - bo
  author: མཚུར་ཕུ་རྒྱལ་ཚབ ༠༤་པ་གྲགས་པ་དོན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.9987742225963508
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN26860:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN26860
      total_pages: 371
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN26860.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9987742225963508
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
